# Generated by Django 4.2.1 on 2023-05-28 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0003_alter_comentario_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacto.comentario'),
        ),
    ]
