# Generated by Django 4.2.1 on 2023-05-29 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0006_alter_comentario_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
