# Generated by Django 4.2.1 on 2023-05-29 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
