# Generated by Django 4.2.1 on 2023-05-29 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0012_alter_comentario_fecha_alter_pregunta_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='pregunta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='contacto.pregunta'),
        ),
    ]
