# Generated by Django 4.2.1 on 2023-06-02 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(upload_to='imgs_personal/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'], code='formato_invalido', message='Sólo se permite formato PNG, JPEG, JPG.')]),
        ),
    ]
