# Generated by Django 4.1.4 on 2023-05-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='satisfaccion',
            field=models.CharField(choices=[('1', 'ALTA'), ('2', 'MEDIA'), ('3', 'BAJA')], default='1', max_length=6),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='logo',
            field=models.ImageField(upload_to='static/img'),
        ),
    ]
